export const CANCEL_MESSAGE = 'CANCEL_MESSAGE';
export const VALIDATE_MESSAGE_REQUESTED = 'VALIDATE_MESSAGE_REQUESTED';
export const VALIDATE_MESSAGE_RECEIVED = 'VALIDATE_MESSAGE_RECEIVED';
export const VALIDATE_MESSAGE_FAILED = 'VALIDATE_MESSAGE_FAILED';

