export const START_QUESTIONS = 'START_QUESTIONS';
export const PROVIDE_ANSWER = 'PROVIDE_ANSWER';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const RESET_QUESTIONS = 'RESET_QUESTIONS';
export const CHANGE_LANG = 'CHANGE_LANG';
