name: publish
on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use yarn
        run: yarn

      - name: Build with yarn
        run: yarn build

      - name: Run tests with yarn
        run: yarn test

      - name: Build storybook
        run: yarn build-storybook

      - name: Create test & storybook
        if: success()
        run: mkdir -p dist/test; mv test-report.html dist/test/index.html; mv storybook-static dist/storybook

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
